In [1]:
import pandas as pd
import numpy as np
print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
import os

os.listdir("../data/raw")

['.gitkeep', 'dynamic_supply_chain_logistics_dataset_with_country.csv']

In [3]:
# Load the supply chain dataset

file_path = "../data/raw/dynamic_supply_chain_logistics_dataset_with_country.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [4]:
# Check number of rows and columns

print("Dataset Shape:", df.shape)
print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])

Dataset Shape: (113097, 18)
Total Rows: 113097
Total Columns: 18

In [5]:
# Display first 5 records

df.head()

,warehouse_inventory_level,handling_equipment_availability,order_fulfillment_status,weather_condition_severity,shipping_costs,supplier_reliability_score,lead_time_days,historical_demand,cargo_condition_status,route_risk_level,customs_clearance_time,disruption_likelihood_score,delay_probability,risk_classification,delivery_time_deviation,product_id,supplier_id,supplier_country
0,985.716862,0.481294,0.761166,0.359066,456.503853,0.986064,2.128009,100.772854,0.777263,1.182116,0.502006,0.506152,0.885291,Moderate Risk,9.110682,P0353,P0353_S1,Greece
1,985.716862,0.481294,0.761166,0.359066,456.503853,0.986064,2.128009,100.772854,0.777263,1.182116,0.502006,0.506152,0.885291,Moderate Risk,9.110682,P0353,P0353_S2,South Korea
2,985.716862,0.481294,0.761166,0.359066,456.503853,0.986064,2.128009,100.772854,0.777263,1.182116,0.502006,0.506152,0.885291,Moderate Risk,9.110682,P0353,P0353_S3,Ethiopia
3,396.700206,0.620780,0.196594,0.230660,640.408205,0.463233,12.608166,5313.738114,0.091839,9.611988,0.966774,0.980784,0.544178,High Risk,8.175281,P0857,P0857_S1,Iran
4,396.700206,0.620780,0.196594,0.230660,640.408205,0.463233,12.608166,5313.738114,0.091839,9.611988,0.966774,0.980784,0.544178,High Risk,8.175281,P0857,P0857_S2,Guatemala

In [6]:
df.shape

(113097, 18)

In [7]:
# Display all column names

print("Total Columns:", len(df.columns))

for i, column in enumerate(df.columns, start=1):
    print(i, column)

Total Columns: 18
1 warehouse_inventory_level
2 handling_equipment_availability
3 order_fulfillment_status
4 weather_condition_severity
5 shipping_costs
6 supplier_reliability_score
7 lead_time_days
8 historical_demand
9 cargo_condition_status
10 route_risk_level
11 customs_clearance_time
12 disruption_likelihood_score
13 delay_probability
14 risk_classification
15 delivery_time_deviation
16 product_id
17 supplier_id
18 supplier_country

In [8]:
# Display dataset information and data types

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113097 entries, 0 to 113096
Data columns (total 18 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   warehouse_inventory_level        113097 non-null  float64
 1   handling_equipment_availability  113097 non-null  float64
 2   order_fulfillment_status         113097 non-null  float64
 3   weather_condition_severity       113097 non-null  float64
 4   shipping_costs                   113097 non-null  float64
 5   supplier_reliability_score       113097 non-null  float64
 6   lead_time_days                   113097 non-null  float64
 7   historical_demand                113097 non-null  float64
 8   cargo_condition_status           113097 non-null  float64
 9   route_risk_level                 113097 non-null  float64
 10  customs_clearance_time           113097 non-null  float64
 11  disruption_likelihood_score      113097 non-null  float64
 12  delay_probability                113097 non-null  float64
 13  risk_classification              113097 non-null  object
 14  delivery_time_deviation          113097 non-null  float64
 15  product_id                       113097 non-null  object
 16  supplier_id                      113097 non-null  object
 17  supplier_country                 113097 non-null  object
dtypes: float64(14), object(4)
memory usage: 15.5+ MB

In [9]:
# Check missing values in each column

missing_values = df.isnull().sum()

print("Missing Values in Each Column:")
print(missing_values)

Missing Values in Each Column:
warehouse_inventory_level          0
handling_equipment_availability    0
order_fulfillment_status           0
weather_condition_severity         0
shipping_costs                     0
supplier_reliability_score         0
lead_time_days                     0
historical_demand                  0
cargo_condition_status             0
route_risk_level                   0
customs_clearance_time             0
disruption_likelihood_score        0
delay_probability                  0
risk_classification                0
delivery_time_deviation            0
product_id                         0
supplier_id                        0
supplier_country                   0
dtype: int64

In [10]:
# Check duplicate records

duplicates = df.duplicated().sum()

print("Total Duplicate Rows:", duplicates)

Total Duplicate Rows: 0

In [11]:
# Statistical summary of numerical columns

df.describe().T

,count,mean,std,min,25%,50%,75%,max
warehouse_inventory_level,113097.0,300.378420,323.860477,1.320000e-12,16.296174,159.126186,542.583327,999.999299
handling_equipment_availability,113097.0,0.303599,0.326512,4.570000e-16,0.017291,0.159642,0.556574,0.999999
order_fulfillment_status,113097.0,0.600992,0.345996,1.320000e-06,0.276788,0.681859,0.938873,1.000000
weather_condition_severity,113097.0,0.497895,0.353455,4.540000e-09,0.144156,0.497966,0.850755,1.000000
shipping_costs,113097.0,459.696347,312.319187,1.000000e+02,153.869113,389.202356,754.167627,999.999853
supplier_reliability_score,113097.0,0.500708,0.353932,6.900000e-10,0.144437,0.502877,0.854850,1.000000
lead_time_days,113097.0,5.216388,4.517152,1.000000e+00,1.237201,3.282951,8.611542,14.999995
historical_demand,113097.0,6019.928559,3429.394766,1.000030e+02,2821.510422,6786.803625,9372.022086,10000.000000
cargo_condition_status,113097.0,0.297268,0.321501,7.260000e-19,0.016840,0.155386,0.540047,1.000000
route_risk_level,113097.0,6.996506,3.236633,4.970000e-05,4.581787,8.376387,9.835310,10.000000
customs_clearance_time,113097.0,2.296624,1.555277,5.000000e-01,0.777328,1.942439,3.749471,5.000000
disruption_likelihood_score,113097.0,0.803447,0.279062,4.770000e-05,0.691751,0.958108,0.998764,1.000000
delay_probability,113097.0,0.699617,0.324297,3.130000e-06,0.456054,0.840807,0.982401,1.000000
delivery_time_deviation,113097.0,5.170553,4.158751,-1.999998e+00,1.259607,6.088516,9.247708,10.000000

In [12]:
# Check unique values for categorical columns

categorical_columns = df.select_dtypes(include="object").columns

for column in categorical_columns:
    print("\nColumn:", column)
    print("Unique Values:", df[column].nunique())
    print(df[column].value_counts().head(10))

Column: risk_classification
Unique Values: 3
risk_classification
High Risk        84368
Moderate Risk    17783
Low Risk         10946
Name: count, dtype: int64

Column: product_id
Unique Values: 1000
product_id
P0459    240
P0969    230
P0712    225
P0811    225
P0515    220
P0872    215
P0852    215
P0593    215
P0830    215
P0202    215
Name: count, dtype: int64

Column: supplier_id
Unique Values: 3524
supplier_id
P0517_S1    56
P0517_S2    56
P0652_S3    50
P0652_S2    50
P0652_S1    50
P0977_S2    49
P0977_S1    49
P0459_S2    48
P0459_S1    48
P0459_S4    48
Name: count, dtype: int64

Column: supplier_country
Unique Values: 94
supplier_country
Vietnam                1896
Dominican Republic     1822
Trinidad and Tobago    1737
UK                     1550
Philippines            1544
Australia              1528
Kyrgyzstan             1523
Bulgaria               1508
Georgia                1497
Myanmar                1495
Name: count, dtype: int64

In [13]:
# Check data types of all columns

print("DATA TYPES")
print("=" * 50)

print(df.dtypes)

DATA TYPES
==================================================
warehouse_inventory_level          float64
handling_equipment_availability    float64
order_fulfillment_status           float64
weather_condition_severity         float64
shipping_costs                     float64
supplier_reliability_score         float64
lead_time_days                     float64
historical_demand                  float64
cargo_condition_status             float64
route_risk_level                   float64
customs_clearance_time             float64
disruption_likelihood_score        float64
delay_probability                  float64
risk_classification                 object
delivery_time_deviation            float64
product_id                          object
supplier_id                         object
supplier_country                    object
dtype: object

In [14]:
# Check class distribution

print("Risk Classification Distribution:")
print(df["risk_classification"].value_counts())

print("\nPercentage Distribution:")
print(
    df["risk_classification"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Risk Classification Distribution:
risk_classification
High Risk        84368
Moderate Risk    17783
Low Risk         10946
Name: count, dtype: int64

Percentage Distribution:
risk_classification
High Risk        74.60
Moderate Risk    15.72
Low Risk          9.68
Name: proportion, dtype: float64

In [ ]:
# Check number of unique products, suppliers and countries

print("Unique Products:",
      df["product_id"].nunique())

print("Unique Suppliers:",
      df["supplier_id"].nunique())

print("Unique Supplier Countries:",
      df["supplier_country"].nunique())

Unique Products: 1000
Unique Suppliers: 3524
Unique Supplier Countries: 94

In [16]:
# Display supplier countries

print(
    df["supplier_country"]
    .value_counts()
    .head(20)
)

supplier_country
Vietnam                   1896
Dominican Republic        1822
Trinidad and Tobago       1737
UK                        1550
Philippines               1544
Australia                 1528
Kyrgyzstan                1523
Bulgaria                  1508
Georgia                   1497
Myanmar                   1495
Jordan                    1489
Colombia                  1487
Romania                   1482
Ethiopia                  1472
Germany                   1469
Bosnia and Herzegovina    1460
Morocco                   1421
Bangladesh                1416
Portugal                  1413
North Macedonia           1387
Name: count, dtype: int64